# Generated by Django 3.1.4 on 2021-10-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_status', models.BooleanField(default=False)),
                ('time_done', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_status', models.BooleanField(default=False)),
                ('time_done', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_status', models.BooleanField(default=False)),
                ('time_done', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_registration',
            fields=[
                ('plate_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('car_owner', models.CharField(max_length=200)),
                ('Owner_Id', models.IntegerField()),
                ('phonenumber', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('Time_done', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otpsend.control')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otpsend.insurance')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otpsend.tax')),
            ],
        ),
    ]
